name: test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Get CMake
        uses: lukka/get-cmake@latest
      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .
        env:
          CC: gcc-10
          CXX: g++-10
      - name: Test
        run: |
          cd build
          ctest -V